import {
    createDefaultTimelineColorSettings,
    DayPlannerMode,
    type DayPlannerSettings,
    DEFAULT_TIMELINE_COLOR_SCHEME,
} from "./settings";

export const DEFAULT_DATE_FORMAT = "YYYYMMDD";
export const DATE_REGEX = /(?<target>{{date:?(?<date>[^}]*)}})/g;

export const DAY_PLANNER_FILENAME = "Day Planner-{{date}}.md";

export const DAY_PLANNER_DEFAULT_CONTENT = `## Day Planner
- [ ] `;

export const VIEW_TYPE_TIMELINE = "timeline";
export const MINUTE_MULTIPLIER = 4;

export const COLORS = {
    ...DEFAULT_TIMELINE_COLOR_SCHEME,
};

export const DEFAULT_SETTINGS: DayPlannerSettings = {
    customFolder: "",
    debug: false,
    mode: DayPlannerMode.File,
    mermaid: false,
    completePastItems: false,
    circularProgress: false,
    nowAndNextInStatusBar: false,
    showTaskNotification: false,
    timelineZoomLevel: 0,
    timelineIcon: "",
    plannerLabel: "Day Planner",
    breakLabel: "BREAK",
    endLabel: "END",
    markCurrent: false,
    correctLabels: false,
    writer: "",
    preserveValues: "",
    hideTimelineValues: "",
    timelineColorBegin: "",
    timelineColorEnd: "",
    timelineHoverColorBegin: "",
    timelineHoverColorEnd: "",
    lineColor: "",
    timelineColors: createDefaultTimelineColorSettings(),
    autoResumeScroll: false,
    autoResumeScrollDelay: 0,
    newDayStartsAt: 0,
    activePlan: {},
};

export const ICONS = [
    "any-key",
    "audio-file",
    "blocks",
    "broken-link",
    "bullet-list",
    "calendar-with-checkmark",
    "checkmark",
    "create-new",
    "cross",
    "cross-in-box",
    "crossed-star",
    "dice",
    "document",
    "documents",
    "dot-network",
    "enter",
    "expand-vertically",
    "filled-pin",
    "folder",
    "gear",
    "go-to-file",
    "hashtag",
    "help",
    "horizontal-split",
    "image-file",
    "info",
    "install",
    "languages",
    "left-arrow",
    "left-arrow-with-tail",
    "lines-of-text",
    "link",
    "logo-crystal",
    "magnifying-glass",
    "microphone",
    "microphone-filled",
    "open-vault",
    "pane-layout",
    "paper-plane",
    "pdf-file",
    "pencil",
    "pin",
    "popup-open",
    "presentation",
    "reset",
    "right-arrow",
    "right-arrow-with-tail",
    "right-triangle",
    "search",
    "sheets-in-box",
    "star",
    "star-list",
    "switch",
    "three-horizontal-bars",
    "trash",
    "two-columns",
    "up-and-down-arrows",
    "uppercase-lowercase-a",
    "vault",
    "vertical-split",
    "vertical-three-dots",
];
