name: CI Test

on:
  push:
    branches: [ main ]
    paths:
      - '**.ts'
      - '**.json'
      - '**.scss'
      - '**.css'
  pull_request:
    paths:
      - '**.ts'
      - '**.json'
      - '**.scss'
      - '**.css'

permissions: read-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Use Node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: '20'
        cache: 'npm'

    - name: Build and Test
      id: build
      run: |
        npm ci
        npm run build
        npm run test

