name: CI Test

on:
  push:
    branches: [ main ]
    paths:
      - '**.ts'
      - '**.json'
      - '**.scss'
      - '**.css'
  pull_request:
    branches: [ main ]
    paths:
      - '**.ts'
      - '**.json'
      - '**.scss'
      - '**.css'

permissions: read-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.5'
        cache: 'npm'

    - name: Build and Test
      id: build
      run: |
        npm install
        npm run build
        npm run test

