name: CI Test

on:
  push:
    branches: [ main ]
    paths:
      - '**.ts'
      - '**.json'
      - '**.scss'
      - '**.css'
  pull_request:
    paths:
      - '**.ts'
      - '**.json'
      - '**.scss'
      - '**.css'

permissions: read-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Use Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '20'
        cache: 'npm'

    - name: Build and Test
      id: build
      run: |
        npm ci
        npm run build
        npm run test

